### ISSUE TITLE
Machines: Add Snapshots Panel

### ISSUE THREAD

**Issue by se1exin** [se1exin/vultr-web-client#10]

**Comment by pedrosimao** [comment]
Hello,
I am very interested in contributing to your project.
Specially for using with snapshots functionality, so as I can deploy multiple similar servers.

Do you need any help?
And is there are website where I can see a demo running?
Regards,

**Comment by se1exin** [comment]
Hi pedrosimao! Thanks for your interest - you can see a demo at https://vultrapp.com. The demo server is currently down for maintenance but it will be back up soon. In the meantime you can run it locally using Vagrant. I will update the readme with instructions

**Comment by pedrosimao** [comment]
I have a ubuntu webserver with Nginx installed. I would like to run on it, instead of installing Vagrant + Scotch box. What apps are actually needed to run it, besides PHP?
